name: Armor AI Doctor (baseline)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "monitor/**"
      - ".github/workflows/armor-ai-doctor.yml"

jobs:
  doctor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Exposed to doctor.py for authenticated GitHub API calls (bypass 60/hr anon limit)
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo state
        run: |
          pwd
          ls -la
          ls -la monitor || true
          head -n 5 monitor/tools.csv || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r monitor/requirements.txt

      - name: Run Armor AI Doctor
        run: |
          mkdir -p artifacts
          python monitor/doctor.py --inventory monitor/tools.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tool-monitor-report
          path: artifacts/
          if-no-files-found: error
