name: Armor AI Doctor (baseline)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "monitor/**"
      - ".github/workflows/armor-ai-doctor.yml"

jobs:
  doctor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug repo state
        run: |
          set -x
          pwd
          ls -la
          ls -la monitor || true
          head -n 5 monitor/tools.csv || true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r monitor/requirements.txt

      - name: Run Armor AI Doctor (self-logged)
        run: |
          set -euxo pipefail
          mkdir -p artifacts
          {
            echo "=== $(date -u) start ==="
            python -V
            python monitor/doctor.py --inventory monitor/tools.csv
            echo "=== $(date -u) end ==="
          } 2>&1 | tee artifacts/doctor.log
          echo "--- alerts.md (first 120) ---" | tee -a artifacts/doctor.log
          [ -f artifacts/alerts.md ] && sed -n '1,120p' artifacts/alerts.md | tee -a artifacts/doctor.log || echo "alerts.md missing" | tee -a artifacts/doctor.log

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tool-monitor-report
          path: artifacts/
          if-no-files-found: warn
