name: Armor AI Doctor (baseline)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "monitor/**"
      - ".github/workflows/armor-ai-doctor.yml"

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Prove logs & artifacts work
        run: |
          set -euxo pipefail
          mkdir -p artifacts
          echo "hello from the runner $(date -u)" | tee artifacts/hello.txt
          echo "repo root contents:"; ls -la
          echo "monitor dir:"; ls -la monitor || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-artifacts
          path: artifacts/
          if-no-files-found: error
