name: Release Evidence
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Evidence
        run: |
          bash scripts/evidence_bundle.sh
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/evidence-*.zip
