name: Release Drafter
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }

# ci-noop-refresh
