name: Release Evidence
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (optional; defaults to latest)"
        required: false
permissions:
  contents: write
  actions: read

jobs:
  evidence:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Resolve tag/prev/sha
        id: meta
        shell: bash
        run: |
          set -euo pipefail
          REPO="${GITHUB_REPOSITORY}"
          TAG_INPUT="${{ github.event.inputs.tag || '' }}"
          if [ -n "$TAG_INPUT" ]; then
            TAG="$TAG_INPUT"
          else
            TAG="${{ github.event.release.tag_name }}"
          fi
          if [ -z "${TAG:-}" ]; then
            TAG="$(gh release view -R "$REPO" --json tagName --jq .tagName)"
          fi
          PREV="$(gh api repos/$REPO/releases --paginate --jq '[.[]|select(.draft==false)]|sort_by(.created_at)|reverse|.[1].tag_name // ""')"
          SHA="$(gh api repos/$REPO/git/ref/tags/$TAG --jq .object.sha)"
          echo "tag=$TAG"  >> "$GITHUB_OUTPUT"
          echo "prev=$PREV" >> "$GITHUB_OUTPUT"
          echo "sha=$SHA"  >> "$GITHUB_OUTPUT"

      - name: Generate evidence
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          REPO="${GITHUB_REPOSITORY}"
          TAG="${{ steps.meta.outputs.tag }}"
          PREV="${{ steps.meta.outputs.prev }}"
          SHA="${{ steps.meta.outputs.sha }}"
          OUT="release-evidence-$TAG.md"

          # Pull core release fields via gh release view (robust by tag, no 404s)
          gh release view "$TAG" -R "$REPO" \
            --json name,tagName,publishedAt,author,url \
            > /tmp/release.json

          {
            echo "# Release Evidence for $TAG"
            echo
            jq -r '
              {name:.name, tag:.tagName, published_at:.publishedAt, author:.author.login, html_url:.url}
              | to_entries[] | "* \(.key): \(.value)"
            ' /tmp/release.json
            echo
            if [ -n "$PREV" ] && [ "$PREV" != "$TAG" ]; then
              echo "## Commits since $PREV"
              gh api "repos/$REPO/compare/$PREV...$TAG" \
                --jq '.commits[] | "* \(.sha[0:7]) \(.commit.author.date) - \(.commit.message|split("\n")[0]) by \(.commit.author.name)"'
            else
              echo "## Commits"
              gh api "repos/$REPO/commits" \
                --jq '.[0:20][] | "* \(.sha[0:7]) - \(.commit.message|split("\n")[0]) by \(.commit.author.name) on \(.commit.author.date)"' || true
            fi
            echo
            echo "## Workflow runs for $TAG"
            gh api "repos/$REPO/actions/runs" -f head_sha="$SHA" \
              --jq '.workflow_runs[] | "* \(.name) • conclusion: \(.conclusion // .status) • run_id=\(.id)"'
          } > "$OUT"

          echo "out=$OUT" >> "$GITHUB_OUTPUT"

      - name: Upload evidence to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          files: ${{ steps.gen.outputs.out }}
