name: Release Evidence
on:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  push:
    tags: [ "v*" ]
  workflow_dispatch:
jobs:
  bundle:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # for keyless signing (cosign)
      contents: write     # upload to release
    steps:
      - uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'
      - name: Build Evidence
        run: |
          bash scripts/evidence_bundle.sh
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/evidence-*.zip

# ci-noop-refresh
